import type { Book, KnowledgeDomain, MentalModel, Exercise, Framework, GraphNode, GraphEdge } from './types'

export const DOMAINS: KnowledgeDomain[] = [
  { id: 'd1', name: 'Freedom',          slug: 'freedom',          description: 'Design a life of autonomy, independence, and optionality',                    icon: 'Bird',       color: '#8B5CF6', bookCount: 3 },
  { id: 'd2', name: 'Wealth',           slug: 'wealth',           description: 'Build financial independence through leverage and scalable systems',           icon: 'TrendingUp', color: '#F59E0B', bookCount: 4 },
  { id: 'd3', name: 'Meaning',          slug: 'meaning',          description: 'Find purpose, pursue what matters, and live intentionally',                   icon: 'Heart',      color: '#EF4444', bookCount: 4 },
  { id: 'd4', name: 'Creation',         slug: 'creation',         description: 'Build products, businesses, art, and lasting work',                           icon: 'Zap',        color: '#3B82F6', bookCount: 4 },
  { id: 'd5', name: 'Focus',            slug: 'focus',            description: 'Master attention, eliminate noise, and do deep work',                         icon: 'Target',     color: '#10B981', bookCount: 3 },
  { id: 'd6', name: 'Business',         slug: 'business',         description: 'Systems, strategy, execution, and scaling',                                   icon: 'Building2',  color: '#6366F1', bookCount: 3 },
  { id: 'd7', name: 'Decision Making',  slug: 'decision-making',  description: 'Think with clarity, reason from first principles, and choose wisely',         icon: 'Brain',      color: '#EC4899', bookCount: 3 },
  { id: 'd8', name: 'Systems Thinking', slug: 'systems-thinking', description: 'See patterns, leverage feedback loops, and design for emergence',             icon: 'Network',    color: '#14B8A6', bookCount: 3 },
]

export const BOOKS: Book[] = [
  {
    id: 'b1',
    title: 'The Millionaire Fastlane',
    author: 'MJ DeMarco',
    coverColor: '#D97706',
    difficulty: 'intermediate',
    publishedYear: 2011,
    readTimeMinutes: 360,
    slug: 'millionaire-fastlane',
    tags: ['wealth-building', 'entrepreneurship', 'freedom', 'leverage'],
    domains: ['wealth', 'freedom', 'business'],
    summary: 'A contrarian guide to wealth that dismantles the conventional "get a job, max your 401k, wait 40 years" script. DeMarco maps three roads to wealth — Sidewalk, Slowlane, and Fastlane — arguing that real freedom comes from building scalable systems, not trading time for money.',
    coreIdea: 'Stop trading time for money. Build scalable businesses, code, or content that generate value while you sleep. The equation for wealth is not income — it is leverage.',
    mentalModels: ['leverage', 'compounding'],
    exercises: ['freedom-number'],
    relatedBooks: ['almanack-naval-ravikant', '4-hour-workweek', '100m-offers'],
    keyConcepts: [
      { id: 'c1', title: 'The Three Roads', description: 'Sidewalk (spend everything), Slowlane (save 40 years), Fastlane (build scalable systems now). Most people are on the wrong road.', icon: 'Map' },
      { id: 'c2', title: 'The Law of Effection', description: 'Wealth is proportional to the number of lives you affect. To get rich, you must affect millions — through a product, service, or content that scales.', icon: 'Users' },
      { id: 'c3', title: 'The CENTS Framework', description: 'Five commandments: Control, Entry barriers, Need-focused, Time-independent, Scale-capable. Any business failing these cannot create real wealth.', icon: 'CheckSquare' },
      { id: 'c4', title: 'Produce, Don\'t Consume', description: 'Most people are consumers. Fastlaners become producers — they build what others consume. Shift your identity from consumer to producer.', icon: 'Factory' },
      { id: 'c5', title: 'Controllable Leverage', description: 'On the Fastlane you control your income ceiling. You own the system. A job gives you zero control — your boss controls the ceiling.', icon: 'Sliders' },
    ],
    reflectionQuestions: [
      { id: 'rq1', question: 'Are you building a business that scales without your direct time, or just a more stressful job?', context: 'The key distinction: does your income require your active hours?' },
      { id: 'rq2', question: 'How many lives does your current work touch? How could you 10x that number?' },
      { id: 'rq3', question: 'What would it mean to own the system in your field, rather than be a component in someone else\'s?' },
      { id: 'rq4', question: 'If your active work stopped tomorrow, would you have any residual income? Why not?' },
    ],
  },
  {
    id: 'b2',
    title: 'The 4-Hour Workweek',
    author: 'Tim Ferriss',
    coverColor: '#0D9488',
    difficulty: 'beginner',
    publishedYear: 2007,
    readTimeMinutes: 300,
    slug: '4-hour-workweek',
    tags: ['freedom', 'productivity', 'entrepreneurship'],
    domains: ['freedom', 'systems-thinking', 'focus'],
    summary: 'Ferriss introduces the DEAL framework — Definition, Elimination, Automation, Liberation — as a blueprint for escaping the traditional deferred-life plan. Through outsourcing, automation, and lifestyle design, he argues you can live like a millionaire without being one.',
    coreIdea: 'Life does not have to be about deferring living until retirement. Use technology, outsourcing, and clear priorities to design your ideal life now — not at 65.',
    mentalModels: ['pareto-principle', 'optionality'],
    exercises: ['ideal-week'],
    relatedBooks: ['millionaire-fastlane', 'deep-work'],
    keyConcepts: [
      { id: 'c6', title: 'The DEAL Framework', description: 'Definition, Elimination, Automation, Liberation. Four sequential steps to lifestyle design and freedom from location.', icon: 'Workflow' },
      { id: 'c7', title: 'The New Rich', description: 'Defined not by net worth but by time and mobility. More freedom than people waiting for retirement with a million dollars.', icon: 'Crown' },
      { id: 'c8', title: 'Fear-Setting', description: 'Instead of goal-setting, write your worst-case scenarios and realize they are survivable. Most fears are paper tigers.', icon: 'Shield' },
      { id: 'c9', title: 'Pareto + Parkinson', description: '80% of results come from 20% of effort. Work expands to fill time allotted. Apply both: identify vital tasks and give them hard deadlines.', icon: 'BarChart2' },
      { id: 'c10', title: 'Mini-Retirements', description: 'Instead of deferring life until 65, distribute mini-retirements throughout your life. Live your dream life in chapters, now.', icon: 'Sun' },
    ],
    reflectionQuestions: [
      { id: 'rq5', question: 'What would you do differently if you only had 2 focused hours of work each day?' },
      { id: 'rq6', question: 'What fears are preventing you from designing your ideal life? Are they realistic?' },
      { id: 'rq7', question: 'What tasks in your life could you eliminate, automate, or delegate entirely?' },
    ],
  },
  {
    id: 'b3',
    title: '$100M Offers',
    author: 'Alex Hormozi',
    coverColor: '#EA580C',
    difficulty: 'intermediate',
    publishedYear: 2021,
    readTimeMinutes: 240,
    slug: '100m-offers',
    tags: ['business-strategy', 'marketing', 'entrepreneurship', 'wealth-building'],
    domains: ['business', 'wealth', 'creation'],
    summary: 'Hormozi breaks down the anatomy of an irresistible offer — one that customers feel foolish rejecting. He systematically deconstructs value, pricing, risk reversal, and framing to show how to create what he calls a Grand Slam Offer.',
    coreIdea: 'The product is secondary. The offer is everything. Engineer your value stack so the perceived value massively outweighs the price, and customers have no rational reason to say no.',
    mentalModels: [],
    exercises: ['offer-builder'],
    relatedBooks: ['millionaire-fastlane', 'zero-to-one'],
    keyConcepts: [
      { id: 'c11', title: 'The Value Equation', description: 'Value = (Dream Outcome × Perceived Likelihood) ÷ (Time Delay × Effort). Maximize the top, minimize the bottom.', icon: 'Calculator' },
      { id: 'c12', title: 'Grand Slam Offer', description: 'An offer so compelling customers feel foolish saying no. It stacks value, eliminates risk, and makes the alternative seem objectively inferior.', icon: 'Trophy' },
      { id: 'c13', title: 'The Value Stack', description: 'Bundle multiple deliverables, bonuses, and guarantees to dramatically increase perceived value without proportionally increasing your cost.', icon: 'Layers' },
      { id: 'c14', title: 'Risk Reversal', description: 'Remove the customer\'s risk entirely. When the seller absorbs all the risk, the only barrier remaining is desire.', icon: 'ShieldCheck' },
      { id: 'c15', title: 'Niche Down', description: 'The riches are in the niches. The more specifically you target a problem for a specific person, the higher the perceived value.', icon: 'Crosshair' },
    ],
    reflectionQuestions: [
      { id: 'rq8', question: 'What is the dream outcome your ideal customer desperately wants?' },
      { id: 'rq9', question: 'What would you need to add to your offer to make it feel irresponsible to say no?' },
      { id: 'rq10', question: 'What risk could you absorb from your customer that would dramatically increase conversions?' },
    ],
  },
  {
    id: 'b4',
    title: 'The Almanack of Naval Ravikant',
    author: 'Eric Jorgenson',
    coverColor: '#7C3AED',
    difficulty: 'beginner',
    publishedYear: 2020,
    readTimeMinutes: 180,
    slug: 'almanack-naval-ravikant',
    tags: ['wealth-building', 'philosophy', 'mindset', 'leverage'],
    domains: ['wealth', 'meaning', 'freedom', 'decision-making'],
    summary: 'A curated collection of Naval Ravikant\'s wisdom on wealth and happiness — assembled from interviews, tweets, and essays. Covers how to build wealth without luck, find inner peace, and develop judgment that compounds over time.',
    coreIdea: 'Wealth is created by building things society wants at scale, with leverage — code, capital, media, or labor. Happiness is a skill and a choice, not a destination you arrive at.',
    mentalModels: ['leverage', 'compounding', 'optionality'],
    exercises: ['values-discovery'],
    relatedBooks: ['psychology-of-money', 'mans-search-for-meaning'],
    keyConcepts: [
      { id: 'c16', title: 'Specific Knowledge', description: 'Knowledge you cannot be taught that feels like play to you and looks like work to others. The foundation of unique value.', icon: 'Key' },
      { id: 'c17', title: 'Four Levers of Leverage', description: 'Labor, capital, code, and media. Code and content are permissionless — anyone can build them without asking anyone\'s permission.', icon: 'Lever' },
      { id: 'c18', title: 'Judgment Over Intelligence', description: 'Good judgment is rarer than raw intelligence. Build it through reading, reflection, and exposure to real consequences.', icon: 'Scale' },
      { id: 'c19', title: 'Happiness as a Skill', description: 'Not a destination — built through peace, meaningful work, and removing desires that distort your perception of the present.', icon: 'Smile' },
      { id: 'c20', title: 'Long-Term Games', description: 'The secret to wealth and great relationships is playing long-term games with long-term people. Reputation and trust compound more than money.', icon: 'Clock' },
    ],
    reflectionQuestions: [
      { id: 'rq11', question: 'What is your specific knowledge — what feels like play to you but looks like work to others?' },
      { id: 'rq12', question: 'Which form of leverage do you currently have access to, and which are you ignoring?' },
      { id: 'rq13', question: 'Are you optimizing for wealth, income, or optionality? Are these currently aligned?' },
      { id: 'rq14', question: 'What does happiness look like for you as a daily practice — not a distant destination?' },
    ],
  },
  {
    id: 'b5',
    title: 'Deep Work',
    author: 'Cal Newport',
    coverColor: '#4338CA',
    difficulty: 'beginner',
    publishedYear: 2016,
    readTimeMinutes: 270,
    slug: 'deep-work',
    tags: ['focus', 'productivity', 'mindset'],
    domains: ['focus', 'creation', 'systems-thinking'],
    summary: 'Newport argues that the ability to focus without distraction on cognitively demanding work is both increasingly rare and increasingly valuable. He provides a philosophy and rules for cultivating this capacity in a distracted world.',
    coreIdea: 'The ability to perform deep work — focused, undistracted cognitive effort — is the superpower of the knowledge economy. Those who develop it will thrive; those who surrender to distraction will fall behind.',
    mentalModels: ['pareto-principle'],
    exercises: ['deep-work-audit'],
    relatedBooks: ['atomic-habits', 'war-of-art'],
    keyConcepts: [
      { id: 'c21', title: 'Deep vs Shallow Work', description: 'Deep: cognitively demanding, distraction-free. Shallow: low-value, logistical. Most knowledge workers spend most of their day in shallow work.', icon: 'Layers' },
      { id: 'c22', title: 'Attention Residue', description: 'Switching tasks leaves a cognitive residue — part of your brain stays on the previous task. Batching and blocking protect your full capacity.', icon: 'Brain' },
      { id: 'c23', title: 'The Any-Benefit Trap', description: 'Most people adopt any tool that provides any benefit, ignoring costs to attention. Evaluate tools by whether they support your highest-value activities.', icon: 'Filter' },
      { id: 'c24', title: 'The Four Philosophies', description: 'Monastic (total isolation), Bimodal (alternating periods), Rhythmic (daily habits), Journalistic (seizing opportunities). Choose what fits your life.', icon: 'Calendar' },
      { id: 'c25', title: 'Productive Meditation', description: 'Use physical activity to solve a single professional problem. Trains concentration and surfaces insights unavailable at a desk.', icon: 'Activity' },
    ],
    reflectionQuestions: [
      { id: 'rq15', question: 'In an average week, what is your deep work to shallow work ratio? What does it reveal?' },
      { id: 'rq16', question: 'What would be different about your career if you tripled your deep work hours per week?' },
      { id: 'rq17', question: 'What is the single distraction that most reliably derails your focus?' },
      { id: 'rq18', question: 'Are you currently working at the ceiling of your ability? If not, what is holding you back?' },
    ],
  },
  {
    id: 'b6',
    title: 'Atomic Habits',
    author: 'James Clear',
    coverColor: '#059669',
    difficulty: 'beginner',
    publishedYear: 2018,
    readTimeMinutes: 240,
    slug: 'atomic-habits',
    tags: ['habits', 'productivity', 'mindset'],
    domains: ['systems-thinking', 'focus', 'meaning'],
    summary: 'Clear presents a comprehensive framework for building good habits and breaking bad ones through tiny, 1% improvements that compound dramatically over time. He introduces the four laws of behavior change and identity-based habits.',
    coreIdea: 'Tiny changes compound into remarkable results. You do not rise to the level of your goals — you fall to the level of your systems. Focus on who you are becoming, not just what you want to achieve.',
    mentalModels: ['compounding', 'systems-vs-goals'],
    exercises: ['life-audit'],
    relatedBooks: ['deep-work', 'mans-search-for-meaning'],
    keyConcepts: [
      { id: 'c26', title: 'Identity-Based Habits', description: 'The most powerful way to change habits is to change your identity. Each action is a vote for the person you want to become.', icon: 'UserCheck' },
      { id: 'c27', title: 'The Four Laws', description: 'Make it obvious (cue), make it attractive (craving), make it easy (response), make it satisfying (reward). Invert each to break bad habits.', icon: 'List' },
      { id: 'c28', title: 'Habit Stacking', description: 'Anchor a new habit to an existing one: "After [current habit], I will [new habit]." Leverages existing neural pathways as scaffolding.', icon: 'Link' },
      { id: 'c29', title: 'Plateau of Latent Potential', description: 'Habits compound invisibly before the breakthrough. Most people quit in the valley of disappointment just before the results become visible.', icon: 'TrendingUp' },
      { id: 'c30', title: 'Goldilocks Rule', description: 'Peak motivation occurs when working at the edge of current ability — not too hard, not too easy. Design habits to live in this zone.', icon: 'Target' },
    ],
    reflectionQuestions: [
      { id: 'rq19', question: 'What identity are your current daily habits voting for? Is that the person you want to become?' },
      { id: 'rq20', question: 'What one habit, done consistently for 12 months, would produce the most significant change in your life?' },
      { id: 'rq21', question: 'Where in your environment are cues triggering bad habits? How could you redesign it?' },
    ],
  },
  {
    id: 'b7',
    title: 'The War of Art',
    author: 'Steven Pressfield',
    coverColor: '#BE185D',
    difficulty: 'beginner',
    publishedYear: 2002,
    readTimeMinutes: 120,
    slug: 'war-of-art',
    tags: ['creativity', 'mindset', 'philosophy'],
    domains: ['creation', 'meaning', 'focus'],
    summary: 'Pressfield personifies the invisible force that blocks creative work as "Resistance" — the enemy of every writer, entrepreneur, and creator. He argues that turning professional and showing up every day is the only antidote.',
    coreIdea: 'Resistance is the universal force that prevents us from doing our most important work. Turning professional — treating your creative work as sacred, showing up every day regardless of feeling — is the only way to defeat it.',
    mentalModels: ['the-resistance'],
    exercises: [],
    relatedBooks: ['deep-work', 'atomic-habits'],
    keyConcepts: [
      { id: 'c31', title: 'Resistance', description: 'The invisible universal force opposing all creative work. It is internal, not external, and strongest when you are closest to your most important work.', icon: 'Shield' },
      { id: 'c32', title: 'Turning Pro', description: 'The amateur plays when inspired. The professional shows up every day regardless of feeling. Turning pro means treating your creative work as a sacred obligation.', icon: 'Briefcase' },
      { id: 'c33', title: 'The Muse', description: 'Creative inspiration is real — but it comes to those who show up first. You don\'t wait for the muse; you create the conditions for the muse to find you.', icon: 'Sparkles' },
      { id: 'c34', title: 'Territorial Orientation', description: 'Hierarchical people create for external approval. Territorial people create for intrinsic value. Only the territorial orientation is sustainable long-term.', icon: 'Map' },
    ],
    reflectionQuestions: [
      { id: 'rq22', question: 'What creative work have you been putting off? What form is Resistance taking in your life?' },
      { id: 'rq23', question: 'Are you an amateur or a professional in your most important work?' },
      { id: 'rq24', question: 'Are you creating for external validation or for intrinsic value? Which feels more true?' },
    ],
  },
  {
    id: 'b8',
    title: 'Man\'s Search for Meaning',
    author: 'Viktor Frankl',
    coverColor: '#475569',
    difficulty: 'intermediate',
    publishedYear: 1946,
    readTimeMinutes: 150,
    slug: 'mans-search-for-meaning',
    tags: ['philosophy', 'mindset'],
    domains: ['meaning', 'decision-making'],
    summary: 'A psychiatrist\'s account of life in Nazi concentration camps and the psychological lessons drawn from surviving the worst conditions imaginable. Frankl presents logotherapy — the idea that the will to meaning is humanity\'s primary drive.',
    coreIdea: 'Everything can be taken from a person except the last human freedom: to choose one\'s attitude toward any circumstance. Finding meaning in suffering transforms it from something to be avoided into something to be embraced.',
    mentalModels: ['inversion'],
    exercises: ['future-self-letter'],
    relatedBooks: ['war-of-art', 'almanack-naval-ravikant'],
    keyConcepts: [
      { id: 'c35', title: 'The Will to Meaning', description: 'Frankl\'s core argument: the primary human drive is not pleasure or power, but the search for meaning. Without meaning, suffering becomes unbearable.', icon: 'Search' },
      { id: 'c36', title: 'Freedom to Choose', description: 'Between stimulus and response there is a space. In that space lies your power to choose your response. This freedom cannot be taken from you.', icon: 'Toggle' },
      { id: 'c37', title: 'Logotherapy', description: 'Therapeutic approach based on finding meaning. Meaning can be found in work, in love, and in unavoidable suffering. Each person must find their own.', icon: 'Heart' },
      { id: 'c38', title: 'Tragic Optimism', description: 'The ability to remain optimistic in spite of suffering, guilt, and death — finding reasons for hope even in the worst circumstances life can present.', icon: 'Sun' },
    ],
    reflectionQuestions: [
      { id: 'rq25', question: 'What gives your work meaning beyond income? Would you do it if the pay were cut in half?' },
      { id: 'rq26', question: 'In what area of your life are you most choosing your response, rather than reacting automatically?' },
      { id: 'rq27', question: 'What suffering in your life could you reframe as something meaningful rather than something to escape?' },
    ],
  },
  {
    id: 'b9',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    coverColor: '#CA8A04',
    difficulty: 'beginner',
    publishedYear: 2020,
    readTimeMinutes: 210,
    slug: 'psychology-of-money',
    tags: ['wealth-building', 'investing', 'mindset'],
    domains: ['wealth', 'decision-making', 'systems-thinking'],
    summary: 'Housel explores the strange and counterintuitive ways people think about money through 19 short stories. Financial success is less about intelligence or knowledge and more about behavior, humility, and long time horizons.',
    coreIdea: 'Financial success is determined more by behavior than by knowledge. Wealth is what you do not spend. The key to good financial outcomes is playing a game you can sustain for decades.',
    mentalModels: ['compounding', 'second-order'],
    exercises: [],
    relatedBooks: ['almanack-naval-ravikant', 'zero-to-one'],
    keyConcepts: [
      { id: 'c39', title: 'Wealth vs Rich', description: 'Rich is visible income and possessions. Wealth is hidden — unspent assets that give you options and freedom. The goal is wealth (optionality), not rich (display).', icon: 'Wallet' },
      { id: 'c40', title: 'The Role of Luck', description: 'Success is more attributable to luck and systemic factors than skill alone. This demands humility in success and compassion in judgment of others.', icon: 'Shuffle' },
      { id: 'c41', title: 'Room for Error', description: 'The most important financial skill is creating margin for error so you survive the unexpected and let compounding work for decades.', icon: 'Shield' },
      { id: 'c42', title: 'Savings Rate', description: 'Your savings rate is more controllable than investment returns. A high savings rate is less about income and more about managing your desire for display.', icon: 'PiggyBank' },
      { id: 'c43', title: 'Long Tails', description: 'A small number of events account for most outcomes. Patience through failures lets you capture the rare, massive wins that dominate long-run returns.', icon: 'TrendingUp' },
    ],
    reflectionQuestions: [
      { id: 'rq28', question: 'Are you building wealth (hidden, compounding) or appearing rich (visible, costly)?' },
      { id: 'rq29', question: 'What financial decision would you make differently if you had a 20-year time horizon instead of a 2-year one?' },
      { id: 'rq30', question: 'What is your "room for error" — how long could you survive financially if your income stopped?' },
    ],
  },
  {
    id: 'b10',
    title: 'Zero to One',
    author: 'Peter Thiel',
    coverColor: '#0369A1',
    difficulty: 'advanced',
    publishedYear: 2014,
    readTimeMinutes: 210,
    slug: 'zero-to-one',
    tags: ['entrepreneurship', 'business-strategy', 'mindset'],
    domains: ['business', 'creation', 'decision-making'],
    summary: 'Thiel\'s contrarian philosophy on building the future through monopolistic innovation. He argues that copying existing markets (1 to n) is incrementalist and competitive, while creating something genuinely new (0 to 1) is the only path to extraordinary value.',
    coreIdea: 'The best businesses create new markets rather than fighting for existing ones. Going from 0 to 1 — creating something truly new — is more valuable and less competitive than copying what already works.',
    mentalModels: ['monopoly-thinking', 'first-principles'],
    exercises: [],
    relatedBooks: ['100m-offers', 'almanack-naval-ravikant'],
    keyConcepts: [
      { id: 'c44', title: '0 to 1 vs 1 to n', description: 'Creating something genuinely new (0→1) is more valuable and less competitive than copying what already exists (1→n). True innovation goes vertical, not horizontal.', icon: 'Plus' },
      { id: 'c45', title: 'Monopoly is the Goal', description: 'Competition destroys profits. The best companies are monopolies — not illegally, but by being so uniquely excellent that competition becomes irrelevant.', icon: 'Crown' },
      { id: 'c46', title: 'Last Mover Advantage', description: 'Better to be the last great company in a market than the first. Durability — generating cash flows far into the future — is what determines real value.', icon: 'Flag' },
      { id: 'c47', title: 'Secrets', description: 'Every great business is built on a secret — something true that few people believe. What important truth do very few people agree with you on?', icon: 'Lock' },
      { id: 'c48', title: 'Power Law', description: 'A small number of choices matter exponentially more than all others combined. One market, one skill, one relationship dominates the long-run distribution.', icon: 'BarChart' },
    ],
    reflectionQuestions: [
      { id: 'rq31', question: 'What important truth do very few people agree with you on? That\'s where your business secret might live.' },
      { id: 'rq32', question: 'Are you building something genuinely new, or competing in an existing market by being slightly better?' },
      { id: 'rq33', question: 'What would you build if you knew it would create a durable monopoly in a market that doesn\'t exist yet?' },
    ],
  },
]

export const MENTAL_MODELS: MentalModel[] = [
  {
    id: 'm1', title: 'Leverage', slug: 'leverage', icon: 'Lever', category: 'wealth',
    description: 'Use a small input to produce a disproportionately large output. Leverage comes in four forms: labor (people work for you), capital (money works for you), code (software works while you sleep), and media (content works forever). The goal is to decouple your time from your income.',
    originBookSlug: 'almanack-naval-ravikant',
    applicationExamples: ['Building a software product that serves 10,000 users with the same effort as serving 1', 'Writing an essay that reaches 1M readers without additional effort per reader', 'Investing capital so money generates returns without active involvement', 'Hiring a team to execute your vision, multiplying your effective output'],
    relatedModels: ['compounding', 'optionality'],
  },
  {
    id: 'm2', title: 'Compounding', slug: 'compounding', icon: 'TrendingUp', category: 'systems',
    description: 'Small improvements repeated consistently produce exponentially larger results over time. This applies to money, skills, relationships, and reputation. The key is time and consistency, not dramatic single actions. Most people overestimate what they can do in a year and underestimate what they can do in a decade.',
    originBookSlug: 'atomic-habits',
    applicationExamples: ['1% daily improvement produces 37x gains over a year (1.01^365 ≈ 37.8)', 'Warren Buffett acquired 99% of his wealth after age 50 due to compounding', 'Writing daily builds a body of work that compounds into authority', 'A trusted reputation compounds through referrals and opportunities'],
    relatedModels: ['leverage', 'systems-vs-goals'],
  },
  {
    id: 'm3', title: 'First Principles Thinking', slug: 'first-principles', icon: 'Cpu', category: 'thinking',
    description: 'Break down complex problems into their fundamental truths and rebuild from scratch, rather than reasoning by analogy. Ask "what is fundamentally true here?" instead of "what has been done before?" This is how you find solutions that others miss because they are constrained by precedent.',
    originBookSlug: 'zero-to-one',
    applicationExamples: ['Elon Musk redesigning rocket cost by questioning raw material prices vs assembled cost', 'Questioning whether you need a physical office, rather than optimizing an existing one', 'Redesigning pricing from scratch based on value delivered, not what competitors charge', 'Building a business model around what customers fundamentally want, ignoring conventions'],
    relatedModels: ['inversion', 'second-order'],
  },
  {
    id: 'm4', title: 'Inversion', slug: 'inversion', icon: 'RefreshCw', category: 'thinking',
    description: 'Instead of asking how to succeed, ask how to avoid failure. Think forward and backward. Identify what would definitively cause the outcome you fear, then avoid those things. Charlie Munger\'s principle: "Invert, always invert." Many hard problems become simple when approached backward.',
    applicationExamples: ['"How do I build a great company?" → "What destroys companies?" — avoid those things', 'Fear-setting: map worst-case scenarios to see they are survivable and reversible', 'Risk management: list what would cause project failure and build processes to prevent each', 'Habit design: identify what would make the habit fail, then remove those obstacles first'],
    relatedModels: ['first-principles', 'second-order'],
  },
  {
    id: 'm5', title: 'Pareto Principle', slug: 'pareto-principle', icon: 'PieChart', category: 'productivity',
    description: '80% of results come from 20% of causes. In business: 20% of customers generate 80% of revenue. In productivity: 20% of tasks produce 80% of value. Identify and concentrate ruthlessly on the vital few. Eliminate or delegate the trivial many.',
    originBookSlug: '4-hour-workweek',
    applicationExamples: ['20% of customers generate 80% of revenue — who should you protect and prioritize?', '20% of your habits produce 80% of your health outcomes', '20% of features generate 80% of usage — which to build and maintain?', '20% of meetings produce 80% of decisions — which to keep, which to cancel?'],
    relatedModels: ['systems-vs-goals', 'leverage'],
  },
  {
    id: 'm6', title: 'Second-Order Thinking', slug: 'second-order', icon: 'GitBranch', category: 'thinking',
    description: 'Most people stop at first-order consequences (this action causes that result). Second-order thinking asks: and then what? Third-order continues further. Most strategic mistakes come from ignoring downstream effects. Ask "and then what?" at least twice for every important decision.',
    applicationExamples: ['Hiring a cheap contractor (saves money) who does poor work (costs more to fix later)', 'Growing revenue fast without systems (more money) leading to chaos (burnout, quality collapse)', 'Saying yes to every opportunity (more income) but spreading thin (mediocre at everything)', 'Low prices attracting bad-fit clients who drain time and lower morale'],
    relatedModels: ['inversion', 'first-principles'],
  },
  {
    id: 'm7', title: 'Skin in the Game', slug: 'skin-in-the-game', icon: 'Shield', category: 'business',
    description: 'People make better decisions when they bear the consequences of their choices. Advice from those without skin in the game is unreliable. Build systems and relationships where decision-makers are exposed to both upside and downside.',
    applicationExamples: ['A financial advisor who invests their own money in what they recommend to clients', 'A founder who takes a pay cut to fund the company they believe in', 'Offering results-based guarantees — you only win when the client wins', 'Being skeptical of consultants and pundits who face no consequences for being wrong'],
    relatedModels: ['second-order', 'inversion'],
  },
  {
    id: 'm8', title: 'Systems vs Goals', slug: 'systems-vs-goals', icon: 'Settings', category: 'habits',
    description: 'Goals are about the outcomes you want. Systems are about the processes that lead to those outcomes. A focus on systems produces continuous improvement; a focus solely on goals produces one-time achievement followed by regression. Fall in love with the system, not the outcome.',
    originBookSlug: 'atomic-habits',
    applicationExamples: ['"Lose 20 pounds" is a goal. "Exercise daily and eat real food" is a system', '"Write a bestseller" is a goal. "Write 500 words every morning" is a system', '"Build a $1M business" is a goal. "Talk to 5 customers and ship one improvement weekly" is a system', 'Identity: becoming the type of person who acts this way consistently, not reaching a milestone'],
    relatedModels: ['compounding', 'pareto-principle'],
  },
  {
    id: 'm9', title: 'The Resistance', slug: 'the-resistance', icon: 'AlertTriangle', category: 'creativity',
    description: 'Steven Pressfield\'s name for the universal, internal force that opposes all creative work and self-improvement. It takes the form of procrastination, self-doubt, rationalization, and distraction. It is strongest precisely when you are closest to your most important work.',
    originBookSlug: 'war-of-art',
    applicationExamples: ['The impulse to check email before starting the most important task of the day', 'Spending days planning and researching instead of actually shipping', 'Feeling intense creative urge the night before a major life commitment', 'The voice that says "I\'ll start tomorrow" — appearing reliably, every single day'],
    relatedModels: ['systems-vs-goals', 'inversion'],
  },
  {
    id: 'm10', title: 'Optionality', slug: 'optionality', icon: 'GitFork', category: 'freedom',
    description: 'Creating and preserving the ability to choose different paths in the future. The value of an option is the asymmetric upside it provides. In life design: make choices that keep more doors open while closing fewer. Avoid irreversible decisions when uncertainty is high.',
    applicationExamples: ['Building an audience before launching a product — keeps all business model options open', 'Learning high-leverage skills (writing, coding, selling) that apply across many careers', 'Maintaining financial margin so you can take career risks others cannot afford to take', 'Remote work + low cost-of-living location preserves financial and geographic optionality'],
    relatedModels: ['leverage', 'second-order'],
  },
  {
    id: 'm11', title: 'Monopoly Thinking', slug: 'monopoly-thinking', icon: 'Crown', category: 'business',
    description: 'The most valuable businesses occupy unique territory where competition is irrelevant. This is not about illegal monopolies — it is about being so uniquely excellent at something specific that customers have no meaningful alternative. Competition is for those who have not differentiated enough.',
    originBookSlug: 'zero-to-one',
    applicationExamples: ['A creator with a unique voice has a monopoly on their specific perspective and audience', 'A software product that becomes a platform others build on — switching costs become prohibitive', 'A specialist who serves a niche so deeply that generalists cannot meaningfully compete', 'A brand so strong that price comparisons become irrelevant to the buying decision'],
    relatedModels: ['first-principles', 'leverage'],
  },
  {
    id: 'm12', title: 'The Flywheel', slug: 'flywheel', icon: 'RefreshCw', category: 'business',
    description: 'A flywheel starts slow and requires significant initial effort. As momentum builds, each push requires less energy for the same output. Great businesses create self-reinforcing loops: growth feeds growth, advantages compound, and the business becomes increasingly difficult to displace.',
    applicationExamples: ['Amazon: lower prices → more customers → more volume → lower costs → lower prices', 'Content creator: content attracts audience → audience gives feedback → better content', 'Network effects: each new user makes the product more valuable for existing users', 'Reputation flywheel: great work → referrals → better clients → more great work'],
    relatedModels: ['compounding', 'leverage'],
  },
]

export const EXERCISES: Exercise[] = [
  {
    id: 'e1', title: 'Values Discovery', slug: 'values-discovery', icon: 'Heart', category: 'self-knowledge',
    estimatedMinutes: 45, difficulty: 'medium',
    goal: 'Identify your 5 core values — the principles that, when honored, make you feel most alive and aligned.',
    instructions: 'This exercise takes you through structured elimination to surface your true core values — not the ones you think you should have, but the ones that are authentically yours. Start broad, narrow ruthlessly, then write what honoring each value looks like in practice.',
    relatedBooks: ['almanack-naval-ravikant'],
    questions: [
      { id: 'eq1', question: 'From this list, write every value that resonates: Adventure, Authenticity, Balance, Creativity, Excellence, Family, Freedom, Growth, Health, Impact, Independence, Integrity, Joy, Learning, Mastery, Meaning, Service, Simplicity, Wealth, Wisdom.', context: 'Do not filter — include everything that resonates even slightly.', placeholder: 'All values that feel true to you...', type: 'textarea' },
      { id: 'eq2', question: 'From your list, which 10 feel most essential?', context: 'Notice which ones you feel emotionally pulled toward, not just intellectually interested in.', placeholder: 'Your top 10 values...', type: 'textarea' },
      { id: 'eq3', question: 'From your top 10, narrow to 5. For each pair, ask: "If I could only keep one, which would I choose?"', context: 'This is uncomfortable — it should be. All your values matter. But some matter more.', placeholder: 'My 5 core values are...', type: 'textarea' },
      { id: 'eq4', question: 'For each of your 5 values, write one sentence: "When I honor this value, I..."', placeholder: 'Value 1: [name] — when I honor this value, I...', type: 'textarea' },
      { id: 'eq5', question: 'Where in your current life are you most violating these values? What is one concrete change you can make this week?', context: 'The gap between stated values and lived values is where most suffering lives.', placeholder: 'The biggest gap between my values and my life is...', type: 'textarea' },
    ],
  },
  {
    id: 'e2', title: 'Freedom Number Calculator', slug: 'freedom-number', icon: 'Calculator', category: 'wealth',
    estimatedMinutes: 30, difficulty: 'easy',
    goal: 'Calculate the exact monthly income you need to cover your ideal lifestyle — your Freedom Number.',
    instructions: 'Most people pursue "more money" without knowing how much is actually enough. This exercise forces radical clarity on your actual needs vs. perceived needs, giving you a concrete financial target to design your work around.',
    relatedBooks: ['millionaire-fastlane'],
    questions: [
      { id: 'eq6', question: 'List your monthly fixed expenses: rent, utilities, subscriptions, insurance, loan payments. Total?', context: 'Be honest — include everything that recurs monthly without fail.', placeholder: 'Fixed expenses total: $', type: 'number' },
      { id: 'eq7', question: 'List your monthly variable expenses: food, transport, entertainment, clothing, health. Total?', context: 'Use your last 3 bank statements for accuracy.', placeholder: 'Variable expenses total: $', type: 'number' },
      { id: 'eq8', question: 'What monthly amount would you spend on experiences, travel, and growth in your ideal life?', context: 'This is your life-enrichment budget. Be honest about what your ideal life actually costs.', placeholder: 'Experience budget: $', type: 'number' },
      { id: 'eq9', question: 'Add 20% to your total for savings and emergency buffer. This is your Freedom Number.', context: 'Freedom Number = (Fixed + Variable + Experiences) × 1.2', placeholder: 'My Freedom Number is: $', type: 'number' },
      { id: 'eq10', question: 'What business model, product, or service could realistically generate this amount? Write 3 plausible paths.', placeholder: '1. ...\n2. ...\n3. ...', type: 'textarea' },
    ],
  },
  {
    id: 'e3', title: 'Ideal Week Design', slug: 'ideal-week', icon: 'Calendar', category: 'freedom',
    estimatedMinutes: 60, difficulty: 'medium',
    goal: 'Design your perfect week from scratch — not the week you have, but the week that would make you feel most alive, productive, and fulfilled.',
    instructions: 'Start from a blank calendar. Ignore current constraints. Design the week you would live if you had full control of your time. Then identify the gap between this ideal and your current reality, and build a plan to close it systematically.',
    relatedBooks: ['4-hour-workweek'],
    questions: [
      { id: 'eq11', question: 'Describe your ideal Monday from 6am to 10pm. What are you doing, with whom, and where?', placeholder: 'My ideal Monday looks like...', type: 'textarea' },
      { id: 'eq12', question: 'What does your ideal Tuesday–Thursday look like? (Deep work, meetings, projects, personal time)', placeholder: 'My ideal workdays look like...', type: 'textarea' },
      { id: 'eq13', question: 'What does your ideal Friday and weekend look like?', placeholder: 'My ideal end of week looks like...', type: 'textarea' },
      { id: 'eq14', question: 'What is the biggest difference between your ideal week and your current week?', context: 'Be specific — name the exact blocks, habits, or commitments that diverge.', placeholder: 'The biggest gaps are...', type: 'textarea' },
      { id: 'eq15', question: 'What is one structural change you can make this month to move your actual week closer to your ideal week?', placeholder: 'This month I will change...', type: 'text' },
    ],
  },
  {
    id: 'e4', title: 'Life Audit', slug: 'life-audit', icon: 'BarChart2', category: 'self-knowledge',
    estimatedMinutes: 30, difficulty: 'easy',
    goal: 'Rate your satisfaction across 8 core life dimensions to see where you are thriving and where you are neglecting yourself.',
    instructions: 'The Life Audit is a regular practice — not a one-time event. Most people drift through life optimizing for the wrong things because they never step back to see the full picture. This exercise gives you that 30,000-foot view.',
    relatedBooks: ['atomic-habits'],
    questions: [
      { id: 'eq16', question: 'Rate your current satisfaction in each area from 1–10: Health & Fitness, Mental/Emotional Wellbeing, Relationships, Career/Work, Finances, Personal Growth, Fun & Recreation, Environment/Home.', context: '1 = severely neglected, 10 = deeply satisfied.', placeholder: 'Health: __ / Mental: __ / Relationships: __ / Career: __ / Finances: __ / Growth: __ / Fun: __ / Environment: __', type: 'textarea' },
      { id: 'eq17', question: 'Which area scored lowest? What is one honest reason it is where it is?', placeholder: 'The lowest area is... because...', type: 'textarea' },
      { id: 'eq18', question: 'If you raised your lowest-scoring area by 3 points, how would your overall life feel different?', placeholder: 'If I improved this area, I would feel...', type: 'textarea' },
      { id: 'eq19', question: 'What is one concrete action you can take this week to begin raising that score?', placeholder: 'This week I will...', type: 'text' },
    ],
  },
  {
    id: 'e5', title: 'Offer Builder', slug: 'offer-builder', icon: 'Trophy', category: 'business',
    estimatedMinutes: 90, difficulty: 'hard',
    goal: 'Construct a Grand Slam Offer for your business, service, or product that eliminates every rational reason to say no.',
    instructions: 'Work through each element of the value equation systematically. Then build your value stack, design risk reversals, and write the final offer statement.',
    relatedBooks: ['100m-offers'],
    questions: [
      { id: 'eq20', question: 'What is the dream outcome your ideal customer desperately wants to achieve or avoid?', context: 'Be specific — not "make more money" but "generate $10k/month from a digital product within 6 months."', placeholder: 'My customer\'s dream outcome is...', type: 'textarea' },
      { id: 'eq21', question: 'What would make your customer believe your offer will actually work for them?', context: 'Testimonials, case studies, your credentials, demonstration, guarantee — what builds perceived likelihood?', placeholder: 'Proof elements I can use...', type: 'textarea' },
      { id: 'eq22', question: 'How quickly can you deliver the result? What could you do to compress the time to first win?', placeholder: 'My current time-to-result is... I could compress it by...', type: 'textarea' },
      { id: 'eq23', question: 'What bonuses, tools, or support could you add to dramatically increase perceived value without proportionally increasing your cost?', placeholder: 'My value stack includes...', type: 'textarea' },
      { id: 'eq24', question: 'What guarantee could you offer that removes all risk from the customer? Write your final offer statement.', placeholder: 'My Grand Slam Offer is: "You get [deliverable] in [timeframe]. If you don\'t get [result], I will [guarantee]."', type: 'textarea' },
    ],
  },
  {
    id: 'e6', title: 'Future Self Letter', slug: 'future-self-letter', icon: 'Mail', category: 'meaning',
    estimatedMinutes: 45, difficulty: 'medium',
    goal: 'Write a letter from your 5-years-in-the-future self describing the life you built and the choices you made.',
    instructions: 'This exercise makes your future self feel real and concrete, reducing temporal discounting. Written from the perspective of your future self looking back, it bypasses current limiting beliefs and activates long-term thinking.',
    relatedBooks: ['mans-search-for-meaning'],
    questions: [
      { id: 'eq25', question: 'It is 5 years from today. Describe where you are living and what your daily life looks like.', placeholder: 'Five years from now, I am living in...', type: 'textarea' },
      { id: 'eq26', question: 'What work are you doing? What did you build or create that you are most proud of?', placeholder: 'The work I am doing is...', type: 'textarea' },
      { id: 'eq27', question: 'What relationships are most important in your life? How did they evolve?', placeholder: 'The relationships that matter most are...', type: 'textarea' },
      { id: 'eq28', question: 'What were the 2–3 most important decisions that shaped how your life turned out?', placeholder: 'The decisions that changed everything were...', type: 'textarea' },
      { id: 'eq29', question: 'What advice does your future self want to give you right now, today?', context: 'Write it as a direct message from your future self to your present self.', placeholder: 'What I wish I had known and done sooner...', type: 'textarea' },
    ],
  },
  {
    id: 'e7', title: 'Deep Work Audit', slug: 'deep-work-audit', icon: 'Target', category: 'focus',
    estimatedMinutes: 30, difficulty: 'easy',
    goal: 'Analyze how much genuine deep work you perform per week and what structural forces are preventing you from doing more.',
    instructions: 'Track your last 5 working days hour by hour. Classify each hour as deep work, shallow work, or distraction. Calculate your deep work ratio. Identify your three biggest sources of distraction. Design a new schedule that protects your peak cognitive hours.',
    relatedBooks: ['deep-work'],
    questions: [
      { id: 'eq30', question: 'Estimate how many hours of genuine deep work you did last week.', context: 'Meetings, email, and "feeling busy" do not count. Only distraction-free, cognitively demanding work counts.', placeholder: 'Hours of deep work last week:', type: 'number' },
      { id: 'eq31', question: 'What are your 3 biggest sources of distraction or interruption during work?', placeholder: '1. ...\n2. ...\n3. ...', type: 'textarea' },
      { id: 'eq32', question: 'When are you at peak cognitive capacity? What does your current schedule look like during those hours?', context: 'Most people have 2–4 peak hours. These should be ruthlessly protected for deep work.', placeholder: 'My peak hours are... Currently I spend them on...', type: 'textarea' },
      { id: 'eq33', question: 'Design a new weekly schedule that protects your peak hours. What would you move, cancel, or batch?', placeholder: 'My new protected deep work blocks would be...', type: 'textarea' },
      { id: 'eq34', question: 'What is one structural change you will implement this week to protect your focus?', placeholder: 'This week I will implement...', type: 'text' },
    ],
  },
]

export const FRAMEWORKS: Framework[] = [
  {
    id: 'f1', title: 'The DEAL Framework', slug: 'deal-framework', originBookSlug: '4-hour-workweek',
    description: 'Tim Ferriss\'s four-step system for escaping the 9-to-5: Define what you actually want, Eliminate what is unimportant, Automate what remains, Liberate yourself from location dependency.',
    steps: [
      { number: 1, title: 'Definition', description: 'Clarify what you want your life to look like. Define your dream lifestyle, your fears, and what you would do if you knew you could not fail.', action: 'Write a detailed description of your ideal day two years from now.' },
      { number: 2, title: 'Elimination', description: 'Apply Pareto and Parkinson. Cut the 80% of tasks that produce 20% of results. Practice a low-information diet. Learn to say no by default.', action: 'List every recurring task. Eliminate anything that does not directly support your top goals.' },
      { number: 3, title: 'Automation', description: 'Build systems and outsource tasks that do not require your personal attention. Automate income through digital products or muse businesses.', action: 'Identify 3 tasks you can delegate or automate this week.' },
      { number: 4, title: 'Liberation', description: 'Negotiate or design location independence. Remove the requirement to be physically present to generate your income.', action: 'Map what would need to change in your income sources to work from anywhere.' },
    ],
  },
  {
    id: 'f2', title: 'The CENTS Framework', slug: 'cents-framework', originBookSlug: 'millionaire-fastlane',
    description: 'MJ DeMarco\'s five commandments for evaluating whether a business can create Fastlane wealth: Control, Entry barriers, Need-focused, Time-independent, Scale-capable.',
    steps: [
      { number: 1, title: 'Control', description: 'Do you control the system? A franchise violates control. A job violates control. You must own and control the asset that generates income.', action: 'Assess: who controls your income ceiling?' },
      { number: 2, title: 'Entry', description: 'Is entry into this business difficult? High barriers to entry mean less competition. If anyone can do it in a weekend, it cannot create wealth.', action: 'Identify what makes your business hard to copy.' },
      { number: 3, title: 'Need', description: 'Does your business solve a real, scalable need? Stop asking "can I make money?" Start asking "can I provide massive value to many people?"', action: 'Define the specific problem you solve and who has it.' },
      { number: 4, title: 'Time', description: 'Is your business time-independent? Can it generate value while you sleep? Any business tied to your hours cannot create Fastlane wealth.', action: 'Map which parts of your income require your active hours and which do not.' },
      { number: 5, title: 'Scale', description: 'Can your business reach thousands or millions? Local businesses often can\'t. The internet removes scale limitations if you build the right product.', action: 'Estimate the realistic upper bound of customers you could serve.' },
    ],
  },
  {
    id: 'f3', title: 'The Four Laws of Behavior Change', slug: 'four-laws', originBookSlug: 'atomic-habits',
    description: 'James Clear\'s Atomic Habits framework: Make it obvious (cue), Make it attractive (craving), Make it easy (response), Make it satisfying (reward). Invert each law to break bad habits.',
    steps: [
      { number: 1, title: 'Make It Obvious', description: 'Design your environment so the cues for your desired habits are visible and prominent. Use implementation intentions: "I will [habit] at [time] in [place]."', action: 'Redesign one environment (desk, kitchen, bedroom) to make one habit\'s cue obvious.' },
      { number: 2, title: 'Make It Attractive', description: 'Bundle the habit you need to do with something you want to do. Use temptation bundling and the culture of your surrounding community.', action: 'Pair one new habit with something genuinely enjoyable.' },
      { number: 3, title: 'Make It Easy', description: 'Reduce friction to the minimum. Design for the two-minute version. Prepare your environment so that the default action is the desired action.', action: 'Reduce the steps to start one habit to under 20 seconds.' },
      { number: 4, title: 'Make It Satisfying', description: 'Give yourself immediate reward after completing the habit. Track your habit to create a visual chain you are motivated not to break.', action: 'Create a simple habit tracker and define your immediate reward.' },
    ],
  },
  {
    id: 'f4', title: 'The Value Equation', slug: 'value-equation', originBookSlug: '100m-offers',
    description: 'Alex Hormozi\'s formula: Value = (Dream Outcome × Perceived Likelihood) ÷ (Time Delay × Effort and Sacrifice). Engineer each variable deliberately.',
    steps: [
      { number: 1, title: 'Maximize Dream Outcome', description: 'Identify and articulate the most desirable end state your customer wants. Make it vivid, specific, and emotionally resonant.', action: 'Write your customer\'s dream outcome in one specific sentence.' },
      { number: 2, title: 'Increase Perceived Likelihood', description: 'Use proof, testimonials, demonstrations, and frameworks to make success feel guaranteed rather than hopeful.', action: 'List every piece of proof you could include in your offer.' },
      { number: 3, title: 'Compress Time Delay', description: 'Show or create quick wins that demonstrate value early. Reduce the time between purchase and first meaningful result.', action: 'Identify the fastest path to your customer\'s first meaningful win.' },
      { number: 4, title: 'Reduce Effort and Sacrifice', description: 'Make the process feel easy and managed. Remove every step the customer would have to figure out themselves.', action: 'List every point of friction and how you could eliminate it.' },
    ],
  },
  {
    id: 'f5', title: 'The 80/20 Priority Stack', slug: '80-20-stack', originBookSlug: '4-hour-workweek',
    description: 'A decision-making framework for identifying and protecting the vital few activities that produce the majority of results, while systematically eliminating or delegating the trivial many.',
    steps: [
      { number: 1, title: 'List All Activities', description: 'Write down every task, project, and commitment you currently have. Include everything — business, personal, recurring, one-off.', action: 'Create an exhaustive list of everything on your plate right now.' },
      { number: 2, title: 'Identify the Vital 20%', description: 'Which 20% of these activities produce 80% of your most valued outcomes — revenue, relationships, wellbeing, growth?', action: 'Circle the top 20% of activities by impact.' },
      { number: 3, title: 'Eliminate the Bottom 20%', description: 'Which 20% of activities consume the most time while producing the least value? These should be eliminated entirely.', action: 'Cancel, stop, or say no to the lowest-value 20% this week.' },
      { number: 4, title: 'Delegate or Automate the Middle 60%', description: 'Anything in the middle that cannot be eliminated should be delegated or automated so your time goes to the vital few.', action: 'Identify one thing from the middle 60% to delegate or automate immediately.' },
    ],
  },
]

export const GRAPH_NODES: GraphNode[] = [
  ...BOOKS.map(b => ({ id: b.slug, label: b.title, type: 'book' as const, color: b.coverColor, size: 20 })),
  ...MENTAL_MODELS.map(m => ({ id: m.slug, label: m.title, type: 'mental_model' as const, color: '#6366F1', size: 14 })),
  ...EXERCISES.map(e => ({ id: e.slug, label: e.title, type: 'exercise' as const, color: '#10B981', size: 12 })),
  ...DOMAINS.map(d => ({ id: d.slug, label: d.name, type: 'domain' as const, color: d.color, size: 24 })),
]

export const GRAPH_EDGES: GraphEdge[] = [
  { source: 'millionaire-fastlane', target: 'leverage' },
  { source: 'millionaire-fastlane', target: 'compounding' },
  { source: 'millionaire-fastlane', target: 'freedom-number' },
  { source: 'almanack-naval-ravikant', target: 'leverage' },
  { source: 'almanack-naval-ravikant', target: 'optionality' },
  { source: 'almanack-naval-ravikant', target: 'values-discovery' },
  { source: 'atomic-habits', target: 'compounding' },
  { source: 'atomic-habits', target: 'systems-vs-goals' },
  { source: 'atomic-habits', target: 'life-audit' },
  { source: 'war-of-art', target: 'the-resistance' },
  { source: '4-hour-workweek', target: 'pareto-principle' },
  { source: '4-hour-workweek', target: 'ideal-week' },
  { source: 'zero-to-one', target: 'monopoly-thinking' },
  { source: 'zero-to-one', target: 'first-principles' },
  { source: 'deep-work', target: 'deep-work-audit' },
  { source: '100m-offers', target: 'offer-builder' },
  { source: 'mans-search-for-meaning', target: 'future-self-letter' },
  { source: 'leverage', target: 'compounding' },
  { source: 'compounding', target: 'systems-vs-goals' },
  { source: 'first-principles', target: 'inversion' },
  { source: 'second-order', target: 'inversion' },
]

export const MOCK_STATS = {
  booksStarted: 3,
  booksCompleted: 1,
  exercisesCompleted: 2,
  currentStreak: 7,
  totalReadingMinutes: 540,
}

export function getBookBySlug(slug: string): Book | undefined {
  return BOOKS.find(b => b.slug === slug)
}

export function getMentalModelBySlug(slug: string): MentalModel | undefined {
  return MENTAL_MODELS.find(m => m.slug === slug)
}

export function getExerciseBySlug(slug: string): Exercise | undefined {
  return EXERCISES.find(e => e.slug === slug)
}

export function getRelatedBooks(slugs: string[]): Book[] {
  return BOOKS.filter(b => slugs.includes(b.slug))
}

export function getBookMentalModels(slugs: string[]): MentalModel[] {
  return MENTAL_MODELS.filter(m => slugs.includes(m.slug))
}

export function getBookExercises(slugs: string[]): Exercise[] {
  return EXERCISES.filter(e => slugs.includes(e.slug))
}

export function getBooksByDomain(domainSlug: string): Book[] {
  return BOOKS.filter(b => b.domains.includes(domainSlug))
}
